#!/usr/bin/env bash
# A script that displays information about subdomains
# shellcheck disable=SC2086

get_subdomain () {

	dig $2.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom=$2 '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'

	return 0
}

get_all_subdomains () {

	subdomains=("www" "lb-01" "web-01" "web-02")

	for subdomain in "${subdomains[@]}"
	do
		dig "$subdomain.$1" | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done

	return 0
}

# determine how many args passed
if [ -z "$2" ]
then
	get_all_subdomains "$1"
else
	get_subdomain "$1" "$2"
fi
