#!/usr/bin/env bash
# A script that installs and configures Nginx on my server

# install nginx
apt-get -y update
apt-get -y install nginx

# make nginx listen on only port 80
ufw allow 'Nginx HTTP'

# start nginx
/etc/init.d/nginx start

# replace the index.html file content 
echo "Hello World!" > /var/www/html/index.html

# configure redirection
sed -i '/server_name _;/a \        location /redirect_me {\n            return 301 https://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }\n' /etc/nginx/sites-available/default

# configure error 404
# write an error file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/not_found.html

# edit configuration to return error file
sed -i '/server_name _;/a\        error_page 404 /not_found.html;\n        location = /not_found.html {\n            root /usr/share/nginx/html;\n            internal;\n         }' /etc/nginx/sites-available/default

# restart nginx
/etc/init.d/nginx reload


