#!/usr/bin/env bash
sed -i '/server_name _;/a\        error_page 404 /not_found.html;\n        location = /not_found.html;\n            root /usr/share/nginx/html;\n            internal;\n         }' ./test
