#!/usr/bin/env bash
# A script that configures HAProxy

sudo apt-get update
sudo apt-get install haproxy

sudo sed -i "\$a\\ENABLED=1" /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}

config="defaults 
  mode http
  timeout connect  5000
  timeout client  10000
  timeout server  10000

frontend myfrontend
  bind 127.0.0.1:80
  default_backend myservers

backend myservers
  balance roundrobin
  server 184230-web-01 54.84.251.92:80
  server 184230-web-02 54.90.50.38:80"

echo "$config" |  sudo tee /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy start
