#!/usr/bin/env bash
# script that fixes bugs on a nginx server
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:80 default_server;/g' /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
