#!/usr/bin/env bash
# a script that fixes a server

# install apache
sudo apt update
sudo apt install apache2

# edit configuration file
IP="$(curl ifconfig.me)"
sudo sed -i "s/#ServerName www.example.com/ServerName $IP/" /etc/apache2/sites-available/000-default.conf

# replace the index.html file content 
echo "Hello Holberton" > /var/www/html/index.html

